#!/usr/bin/env sh

set -e

ROOT_DIR=`pwd`
BUILD_DIR=${ROOT_DIR}/build-dir

. $(dirname $0)/set-versions

tar xzf pcre-${PCRE_VERSION}.tar.gz
PCRE_SRC_DIR=`pwd`/pcre-${PCRE_VERSION}
PCRE_DIR=`pwd`/pcre
cd ${PCRE_SRC_DIR}
./configure --prefix=${PCRE_DIR}
make
make install

cd ${ROOT_DIR}

APACHE2_DIR=httpd-${APACHE2_VERSION}

tar xzf httpd-${APACHE2_VERSION}.tar.gz

mkdir -p ${APACHE2_DIR}/srclib/apr
tar xzf apr-${APR_VERSION}.tar.gz --directory ${APACHE2_DIR}/srclib/apr --strip-components 1

mkdir -p ${APACHE2_DIR}/srclib/apr-util
tar xzf apr-util-${APR_UTIL_VERSION}.tar.gz --directory ${APACHE2_DIR}/srclib/apr-util --strip-components 1

cd ${APACHE2_DIR}
./configure --with-pcre=${PCRE_DIR} --prefix=${BUILD_DIR}
make
make install
