#!/usr/bin/env sh

set -e

BUILD_DIR=`pwd`/build-dir
INSTALL_DIR=$1
ORIGINAL_APACHE2_DIR=`cat APACHE2_DIR`
INSTALL_APACHE2_DIR=${INSTALL_DIR}/apache2

cp -rT ${BUILD_DIR} ${INSTALL_DIR}
cd ${INSTALL_APACHE2_DIR}
find conf -type f -print0 | xargs -0 sed -i -e s,${ORIGINAL_APACHE2_DIR},${INSTALL_APACHE2_DIR},g
